<?php
/**
 * ReachApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * wh2o-api
 *
 * The API for American Whitewater.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReachApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReachApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for reachGet
     *
     * Returns a list of reaches (rivers, creeks, streams)..
     *
     */
    public function testReachGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reachIdAccidentGet
     *
     * Gets all the accidents for a reach by ID..
     *
     */
    public function testReachIdAccidentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reachIdArticleGet
     *
     * Gets all the articles for a reach by ID..
     *
     */
    public function testReachIdArticleGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reachIdDelete
     *
     * Deletes a reach by ID..
     *
     */
    public function testReachIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reachIdEventGet
     *
     * Gets all the events for a reach by ID..
     *
     */
    public function testReachIdEventGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reachIdFeatureGet
     *
     * Gets all the features for a reach by ID..
     *
     */
    public function testReachIdFeatureGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reachIdGageGet
     *
     * Gets all the gages for a reach by ID..
     *
     */
    public function testReachIdGageGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reachIdGet
     *
     * Gets a reach by ID..
     *
     */
    public function testReachIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reachIdPostGet
     *
     * Gets all the posts for a reach by ID..
     *
     */
    public function testReachIdPostGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reachIdPut
     *
     * Updates a reach by ID..
     *
     */
    public function testReachIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reachPost
     *
     * Creates a new reach..
     *
     */
    public function testReachPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reachStateStateGet
     *
     * Gets all the reaches for U.S. State..
     *
     */
    public function testReachStateStateGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
