preset: laravel

enabled:

disabled:
  - phpdoc_summary
  - phpdoc_var_without_name
  - post_increment
  - concat_without_spaces
  - unused_use

finder:
  not-name:
    - index.php
    - server.php
  exclude:
    - "tests"
    - "storage"
    - "vendor"