version: '3.7'
services:
  db:
    restart: always
    container_name: db
    image: postgres:latest
    volumes:
      - /usr/lib/postgres/pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - default
networks:
  default:
    driver: bridge
