//
// Accident.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Accident: Codable, JSONEncodable, Hashable {

    /** The auto-generated id of the accident */
    internal var id: Int?
    /** The title of the accident */
    internal var title: String?

    internal init(id: Int? = nil, title: String? = nil) {
        self.id = id
        self.title = title
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
    }
}

