//
// Article.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Article: Codable, JSONEncodable, Hashable {

    /** The auto-generated id of the article */
    internal var id: Int?
    /** The name of the article */
    internal var title: String?
    internal var author: User?

    internal init(id: Int? = nil, title: String? = nil, author: User? = nil) {
        self.id = id
        self.title = title
        self.author = author
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case author
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(author, forKey: .author)
    }
}

