/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The auto-generated id of the accident
 * @param title The title of the accident
 */


data class Accident (

    /* The auto-generated id of the accident */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* The title of the accident */
    @Json(name = "title")
    val title: kotlin.String? = null

)

