/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The auto-generated id of the article
 * @param title The name of the article
 * @param author 
 */


data class Article (

    /* The auto-generated id of the article */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* The name of the article */
    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "author")
    val author: User? = null

)

