/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Reach

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The auto-generated id of the event
 * @param name The name of the event
 * @param reach 
 */


data class Event (

    /* The auto-generated id of the event */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* The name of the event */
    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "reach")
    val reach: Reach? = null

)

