/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The auto-generated id of the feature
 * @param name The name of the feature
 * @param description 
 * @param distance 
 * @param character 
 * @param reachId 
 */


data class Feature (

    /* The auto-generated id of the feature */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* The name of the feature */
    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "distance")
    val distance: java.math.BigDecimal? = null,

    @Json(name = "character")
    val character: Feature.Character? = null,

    @Json(name = "reachId")
    val reachId: java.math.BigDecimal? = null

) {

    /**
     * 
     *
     * Values: access,hazard,other,surfSpot,portage,putin,rapid,takeout,waterfall
     */
    @JsonClass(generateAdapter = false)
    enum class Character(val value: kotlin.String) {
        @Json(name = "access") access("access"),
        @Json(name = "hazard") hazard("hazard"),
        @Json(name = "other") other("other"),
        @Json(name = "surf_spot") surfSpot("surf_spot"),
        @Json(name = "portage") portage("portage"),
        @Json(name = "putin") putin("putin"),
        @Json(name = "rapid") rapid("rapid"),
        @Json(name = "takeout") takeout("takeout"),
        @Json(name = "waterfall") waterfall("waterfall");
    }
}

