/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The auto-generated id of the gage
 * @param name The name of the gage
 */


data class Gage (

    /* The auto-generated id of the gage */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* The name of the gage */
    @Json(name = "name")
    val name: kotlin.String? = null

)

