/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Reach
import org.openapitools.client.models.User

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The auto-generated id of the post
 * @param title The title the post
 * @param content The content of the post
 * @param published Whether the post is published or not
 * @param createdAt 
 * @param updatedAt 
 * @param author 
 * @param reach 
 */


data class Post (

    /* The auto-generated id of the post */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /* The title the post */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* The content of the post */
    @Json(name = "content")
    val content: kotlin.String? = null,

    /* Whether the post is published or not */
    @Json(name = "published")
    val published: kotlin.Boolean? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "author")
    val author: User? = null,

    @Json(name = "reach")
    val reach: Reach? = null

)

