/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Event
import org.openapitools.client.models.Feature
import org.openapitools.client.models.Gage
import org.openapitools.client.models.Permit
import org.openapitools.client.models.Post

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param river The name of the reach
 * @param section The section of the reach
 * @param id The auto-generated id of the reach
 * @param alternateName 
 * @param `abstract` 
 * @param averageGradient 
 * @param maximumGradient 
 * @param minimumGradient 
 * @param county 
 * @param description 
 * @param grade 
 * @param state 
 * @param zipcode 
 * @param length 
 * @param events 
 * @param features 
 * @param gages 
 * @param posts 
 * @param permit 
 */


data class Reach (

    /* The name of the reach */
    @Json(name = "river")
    val river: kotlin.String,

    /* The section of the reach */
    @Json(name = "section")
    val section: kotlin.String,

    /* The auto-generated id of the reach */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "alternate_name")
    val alternateName: kotlin.String? = null,

    @Json(name = "abstract")
    val `abstract`: kotlin.String? = null,

    @Json(name = "average_gradient")
    val averageGradient: java.math.BigDecimal? = null,

    @Json(name = "maximum_gradient")
    val maximumGradient: java.math.BigDecimal? = null,

    @Json(name = "minimum_gradient")
    val minimumGradient: java.math.BigDecimal? = null,

    @Json(name = "county")
    val county: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "grade")
    val grade: kotlin.String? = null,

    @Json(name = "state")
    val state: kotlin.String? = null,

    @Json(name = "zipcode")
    val zipcode: kotlin.String? = null,

    @Json(name = "length")
    val length: java.math.BigDecimal? = null,

    @Json(name = "events")
    val events: kotlin.collections.List<Event>? = null,

    @Json(name = "features")
    val features: kotlin.collections.List<Feature>? = null,

    @Json(name = "gages")
    val gages: kotlin.collections.List<Gage>? = null,

    @Json(name = "posts")
    val posts: kotlin.collections.List<Post>? = null,

    @Json(name = "permit")
    val permit: Permit? = null

)

