/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Article
import org.openapitools.client.models.Post

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param email 
 * @param name 
 * @param posts 
 * @param articles 
 */


data class User (

    @Json(name = "id")
    val id: kotlin.Int? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "posts")
    val posts: kotlin.collections.List<Post>? = null,

    @Json(name = "articles")
    val articles: kotlin.collections.List<Article>? = null

)

