//
// Event.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct Event: Codable, JSONEncodable, Hashable {

    /** The auto-generated id of the event */
    internal var id: Int?
    /** The name of the event */
    internal var name: String?
    internal var reach: Reach?

    internal init(id: Int? = nil, name: String? = nil, reach: Reach? = nil) {
        self.id = id
        self.name = name
        self.reach = reach
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case reach
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(reach, forKey: .reach)
    }
}

