//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

internal struct User: Codable, JSONEncodable, Hashable {

    internal var id: Int?
    internal var email: String?
    internal var name: String?
    internal var posts: [Post]?
    internal var articles: [Article]?

    internal init(id: Int? = nil, email: String? = nil, name: String? = nil, posts: [Post]? = nil, articles: [Article]? = nil) {
        self.id = id
        self.email = email
        self.name = name
        self.posts = posts
        self.articles = articles
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case name
        case posts
        case articles
    }

    // Encodable protocol methods

    internal func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(posts, forKey: .posts)
        try container.encodeIfPresent(articles, forKey: .articles)
    }
}

